### PR TITLE
Adding min_level to avoid log some messages unless specified - BIS

### PR DESCRIPTION
**Pull request by saniales**
Fixes broken #5

### CODE REVIEW

**Comment by saniales** [comment]
Resolved conflicts

**Comment by shuLhan** [comment]
You need to rebase with master first to fix conflict due to merge from #5 and push again.

**Comment by saniales** [comment]
I merged using UI

**Review by shuLhan — APPROVED** [review]

**Comment by shuLhan** [comment]
This patch has been cherry-picked manually on master.  Thank you.

**Pull request closed without merging**
